"""Adiciona coluna is_admin ao modelo User

Revision ID: fa3cf3c10ef7
Revises: 
Create Date: 2025-01-27 14:37:51.110724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3cf3c10ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('users',
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
